# Generated by Django 4.1.1 on 2022-09-17 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_distribution_date_finish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='code_provider',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='tag',
        ),
        migrations.AddField(
            model_name='distribution',
            name='code_provider_client',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_code_provider', to='todos.client', verbose_name='Код оператора клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distribution',
            name='tag_client',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_tag', to='todos.client', verbose_name='тэг клиента'),
            preserve_default=False,
        ),
    ]
