# Generated by Django 4.1.1 on 2022-09-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_remove_distribution_code_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='code_provider_client',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='tag_client',
        ),
        migrations.AddField(
            model_name='distribution',
            name='code_provider',
            field=models.IntegerField(default=1, verbose_name='Код оператора клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distribution',
            name='tag',
            field=models.CharField(default=1, max_length=100, verbose_name='тэг клиента'),
            preserve_default=False,
        ),
    ]
